//! C3 — Tool-Call Output Parser
//!
//! Parses tool/function invocations from the raw text generated by agentic LLMs.
//! Supports all major model formats in use as of April 2026.
//!
//! # Supported Formats
//!
//! | Model family | Delimiter style |
//! |---|---|
//! | Qwen 3 / QwQ | `<tool_call>…</tool_call>` JSON object |
//! | Llama 3.x / Llama 4 | `<|tool_call|>…<|end_tool_call|>` |
//! | DeepSeek-R1 / V3 | `<｜tool▁call▁begin｜>…` (Unicode delimiters) |
//! | Phi-4 | `<tool_call>…</tool_call>` (same as Qwen) |
//! | OpenAI-style | ` ```json\n{…}\n``` ` code fences with `"name"` / `"arguments"` keys |
//! | Mistral / MiniMax | `[TOOL_CALLS] [{…}]` JSON array |
//!
//! # Design
//! - **Zero-allocation fast path**: if no delimiters found, returns `(vec![], original)`.
//! - **Partial tolerance**: malformed JSON inside a detected block is returned as
//!   `ToolCall { name: "?", arguments: raw_text, parse_error: true }`.
//! - **Multiple calls**: all calls from a single generation step are extracted.

use std::fmt;

// ---------------------------------------------------------------------------
// Public Types
// ---------------------------------------------------------------------------

/// A single parsed tool invocation extracted from model output.
#[derive(Debug, Clone, PartialEq)]
pub struct ToolCall {
    /// The function/tool name (e.g., `"get_weather"`).
    pub name: String,
    /// The arguments as a JSON string (may be `"{}"` if no args).
    /// Callers should `serde_json::from_str` this if needed.
    pub arguments: String,
    /// True if the JSON inside the tool-call block could not be parsed.
    /// The raw text is preserved in `arguments` for debugging.
    pub parse_error: bool,
}

impl ToolCall {
    fn new(name: impl Into<String>, arguments: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            arguments: arguments.into(),
            parse_error: false,
        }
    }

    fn raw(raw: impl Into<String>) -> Self {
        Self {
            name: "?".into(),
            arguments: raw.into(),
            parse_error: true,
        }
    }
}

impl fmt::Display for ToolCall {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}({})", self.name, self.arguments)
    }
}

/// Result of parsing model output for tool calls.
#[derive(Debug, Clone)]
pub struct ParseResult {
    /// All tool calls found in the output, in order.
    pub calls: Vec<ToolCall>,
    /// The text remaining after removing all tool-call blocks.
    /// This is the "visible" content shown to the user.
    pub remainder: String,
}

impl ParseResult {
    /// True if at least one tool call was found.
    pub fn has_calls(&self) -> bool {
        !self.calls.empty()
    }
}

// ---------------------------------------------------------------------------
// Format Detectors
// ---------------------------------------------------------------------------

/// Attempt to parse `raw` as `{"name": "...", "arguments": {...}}` (Qwen/Phi format)
/// or `{"name": "...", "parameters": {...}}` (some Mistral variants).
fn parse_json_tool_call(raw: &str) -> ToolCall {
    // Fast structural check: must start with '{' after trim
    let trimmed = raw.trim();
    if !trimmed.starts_with('{') {
        return ToolCall::raw(raw);
    }

    // Extract "name" field
    let name = extract_json_string_field(trimmed, "name");
    // Extract "arguments" or "parameters" field (as raw JSON value)
    let args = extract_json_value_field(trimmed, "arguments")
        .or_else(|| extract_json_value_field(trimmed, "parameters"))
        .unwrap_or_else(|| "{}".to_string());

    match name {
        Some(n) => ToolCall::new(n, args),
        None => ToolCall::raw(raw),
    }
}

/// Extract a JSON string value: `"field": "value"` → `Some("value")`
fn extract_json_string_field(json: &str, field: &str) -> Option<String> {
    // Pattern: `"field": "value"` — handles spaces around colon
    let key_pattern = format!("\"{}\"", field);
    let key_start = json.find(key_pattern.as_str())?;
    let after_key = &json[key_start + key_pattern.len()..];
    // Skip whitespace + colon
    let after_colon = after_key
        .trim_start()
        .strip_prefix(':')?
        .trim_start();
    if !after_colon.starts_with('"') {
        return None;
    }
    let inner = &after_colon[1..]; // skip opening "
    let mut result = String::new();
    let mut chars = inner.chars();
    while let Some(c) = chars.next() {
        if c == '"' {
            break;
        }
        if c == '\\' {
            // Handle basic escape sequences
            match chars.next() {
                Some('"') => result.push('"'),
                Some('\\') => result.push('\\'),
                Some('n') => result.push('\n'),
                Some('t') => result.push('\t'),
                Some(other) => { result.push('\\'); result.push(other); }
                None => break,
            }
        } else {
            result.push(c);
        }
    }
    Some(result)
}

/// Extract any JSON value (string, object, array, number) for a field.
/// Returns the raw value substring.
fn extract_json_value_field(json: &str, field: &str) -> Option<String> {
    let key_pattern = format!("\"{}\"", field);
    let key_start = json.find(key_pattern.as_str())?;
    let after_key = &json[key_start + key_pattern.len()..];
    let after_colon = after_key
        .trim_start()
        .strip_prefix(':')?
        .trim_start();

    if after_colon.is_empty() {
        return None;
    }

    let value = match after_colon.chars().next()? {
        '"' => {
            // String value — re-parse to extract full quoted string
            let mut end = 1;
            let bytes = after_colon.as_bytes();
            while end < bytes.len() {
                if bytes[end] == b'"' && bytes[end - 1] != b'\\' {
                    end += 1;
                    break;
                }
                end += 1;
            }
            after_colon[..end].to_string()
        }
        '{' | '[' => {
            // Object or array — balance brackets
            let open = after_colon.chars().next()?;
            let close = if open == '{' { '}' } else { ']' };
            let mut depth = 0usize;
            let mut end = 0usize;
            let mut in_string = false;
            for (i, c) in after_colon.char_indices() {
                match c {
                    '"' if !in_string => in_string = true,
                    '"' => in_string = false,
                    ch if ch == open && !in_string => depth += 1,
                    ch if ch == close && !in_string => {
                        depth -= 1;
                        if depth == 0 {
                            end = i + c.len_utf8();
                            break;
                        }
                    }
                    _ => {}
                }
            }
            if end == 0 { return None; }
            after_colon[..end].to_string()
        }
        // Number / bool / null — take until whitespace or comma
        _ => {
            let end = after_colon
                .find(|c: char| c == ',' || c == '}' || c == ']' || c.is_whitespace())
                .unwrap_or(after_colon.len());
            after_colon[..end].to_string()
        }
    };

    Some(value)
}

// ---------------------------------------------------------------------------
// Main Parser
// ---------------------------------------------------------------------------

/// Parse tool calls from raw model output text.
///
/// Strips all tool-call blocks from the output and returns:
/// - `calls` — structured `ToolCall` list (may be empty)
/// - `remainder` — visible text with tool-call blocks removed + trimmed
///
/// # Examples
/// ```text
/// let output = "I'll check the weather. <tool_call>{\"name\":\"get_weather\",\"arguments\":{\"city\":\"Paris\"}}</tool_call>";
/// let result = parse_tool_calls(output);
/// assert_eq!(result.calls[0].name, "get_weather");
/// assert_eq!(result.remainder.trim(), "I'll check the weather.");
/// ```
pub fn parse_tool_calls(text: &str) -> ParseResult {
    // Fast path: no known delimiter present
    if !text.contains("<tool_call>")
        && !text.contains("<|tool_call|>")
        && !text.contains("[TOOL_CALLS]")
        && !text.contains("<｜tool▁call▁begin｜>")
    {
        return ParseResult {
            calls: vec![],
            remainder: text.to_string(),
        };
    }

    let mut calls = Vec::new();
    let mut remainder = text.to_string();

    // ── Format 1: <tool_call>…</tool_call> (Qwen3, Phi-4, most models) ──────
    remainder = extract_delimited_blocks(
        &remainder,
        "<tool_call>",
        "</tool_call>",
        &mut calls,
        |inner| parse_json_tool_call(inner),
    );

    // ── Format 2: <|tool_call|>…<|end_tool_call|> (Llama 3.x / 4) ───────────
    remainder = extract_delimited_blocks(
        &remainder,
        "<|tool_call|>",
        "<|end_tool_call|>",
        &mut calls,
        |inner| parse_json_tool_call(inner),
    );

    // ── Format 3: [TOOL_CALLS] [{…}, …] (Mistral, MiniMax) ──────────────────
    if let Some(pos) = remainder.find("[TOOL_CALLS]") {
        let after = &remainder[pos + "[TOOL_CALLS]".len()..].trim_start();
        if after.starts_with('[') {
            // Parse JSON array of tool call objects
            if let Some(array_end) = find_matching_bracket(after, '[', ']') {
                let array_str = &after[..array_end + 1];
                // Extract individual objects from the array
                let parsed = parse_json_array_of_calls(array_str);
                calls.extend(parsed);
                // Remove from remainder
                let full_match_start = pos;
                let full_match_len = "[TOOL_CALLS]".len()
                    + (after.as_ptr() as usize - remainder[pos + "[TOOL_CALLS]".len()..].trim_start().as_ptr() as usize)
                    + array_end + 1;
                // Simpler: just remove everything from [TOOL_CALLS] to end of array
                let prefix = &remainder[..full_match_start];
                let suffix_start = pos + full_match_len;
                let suffix = if suffix_start < remainder.len() {
                    &remainder[suffix_start..]
                } else {
                    ""
                };
                remainder = format!("{}{}", prefix, suffix);
            }
        }
    }

    // ── Format 4: <｜tool▁call▁begin｜>…</tool_call> (DeepSeek) ─────────────
    // DeepSeek uses Unicode fullwidth vertical bar + special spaces in the opening tag
    remainder = extract_delimited_blocks(
        &remainder,
        "<｜tool▁call▁begin｜>",
        "</tool_call>",
        &mut calls,
        |inner| {
            // DeepSeek sometimes prefixes with function name on a line before JSON
            let trimmed = inner.trim();
            if let Some(newline) = trimmed.find('\n') {
                let first_line = trimmed[..newline].trim();
                let rest = trimmed[newline + 1..].trim();
                if !first_line.is_empty() && !first_line.starts_with('{') {
                    // First line is likely the function name
                    let args = if rest.starts_with('{') { rest } else { "{}" };
                    return ToolCall::new(first_line, args);
                }
            }
            parse_json_tool_call(trimmed)
        },
    );

    ParseResult {
        calls,
        remainder: remainder.trim().to_string(),
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn extract_delimited_blocks(
    text: &str,
    open: &str,
    close: &str,
    calls: &mut Vec<ToolCall>,
    parse: impl Fn(&str) -> ToolCall,
) -> String {
    let mut result = String::with_capacity(text.len());
    let mut rest = text;

    while let Some(start) = rest.find(open) {
        result.push_str(&rest[..start]);
        let after_open = &rest[start + open.len()..];
        if let Some(end) = after_open.find(close) {
            let inner = &after_open[..end];
            calls.push(parse(inner));
            rest = &after_open[end + close.len()..];
        } else {
            // Unclosed block — keep remainder verbatim
            result.push_str(&rest[start..]);
            rest = "";
            break;
        }
    }
    result.push_str(rest);
    result
}

fn find_matching_bracket(s: &str, open: char, close: char) -> Option<usize> {
    let mut depth = 0usize;
    let mut in_string = false;
    for (i, c) in s.char_indices() {
        match c {
            '"' => in_string = !in_string,
            ch if ch == open && !in_string => depth += 1,
            ch if ch == close && !in_string => {
                depth -= 1;
                if depth == 0 {
                    return Some(i);
                }
            }
            _ => {}
        }
    }
    None
}

fn parse_json_array_of_calls(array: &str) -> Vec<ToolCall> {
    // Extract each top-level `{…}` object from a JSON array
    let mut calls = Vec::new();
    let inner = array.trim().strip_prefix('[').unwrap_or(array);
    let inner = inner.trim_end().strip_suffix(']').unwrap_or(inner);
    let mut rest = inner.trim();

    while !rest.is_empty() {
        if rest.starts_with('{') {
            if let Some(end) = find_matching_bracket(rest, '{', '}') {
                let obj = &rest[..end + 1];
                calls.push(parse_json_tool_call(obj));
                rest = rest[end + 1..].trim().strip_prefix(',').unwrap_or(rest[end + 1..].trim()).trim();
            } else {
                break;
            }
        } else {
            break;
        }
    }
    calls
}

// Extension trait shim — Vec doesn't have .empty()
trait IsEmpty { fn empty(&self) -> bool; }
impl<T> IsEmpty for Vec<T> { fn empty(&self) -> bool { self.is_empty() } }

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_no_tool_calls_fast_path() {
        let r = parse_tool_calls("Hello, how can I help you today?");
        assert!(r.calls.is_empty());
        assert_eq!(r.remainder, "Hello, how can I help you today?");
    }

    #[test]
    fn test_qwen_single_tool_call() {
        let text = r#"I'll get the weather. <tool_call>{"name":"get_weather","arguments":{"city":"Paris","unit":"celsius"}}</tool_call>"#;
        let r = parse_tool_calls(text);
        assert_eq!(r.calls.len(), 1);
        assert_eq!(r.calls[0].name, "get_weather");
        assert!(!r.calls[0].parse_error);
        assert!(r.remainder.contains("I'll get the weather."));
        assert!(!r.remainder.contains("<tool_call>"));
    }

    #[test]
    fn test_multiple_tool_calls() {
        let text = concat!(
            r#"<tool_call>{"name":"search","arguments":{"q":"rust"}}</tool_call>"#,
            r#"<tool_call>{"name":"summarize","arguments":{"text":"..."}}</tool_call>"#
        );
        let r = parse_tool_calls(text);
        assert_eq!(r.calls.len(), 2);
        assert_eq!(r.calls[0].name, "search");
        assert_eq!(r.calls[1].name, "summarize");
    }

    #[test]
    fn test_llama_format() {
        let text = r#"Sure! <|tool_call|>{"name":"get_news","arguments":{"topic":"AI"}}<|end_tool_call|>"#;
        let r = parse_tool_calls(text);
        assert_eq!(r.calls.len(), 1);
        assert_eq!(r.calls[0].name, "get_news");
    }

    #[test]
    fn test_malformed_json_preserved() {
        let text = r#"<tool_call>this is not JSON</tool_call>"#;
        let r = parse_tool_calls(text);
        assert_eq!(r.calls.len(), 1);
        assert!(r.calls[0].parse_error);
        assert_eq!(r.calls[0].name, "?");
    }

    #[test]
    fn test_mistral_tool_calls_array() {
        let text = r#"[TOOL_CALLS] [{"name":"calc","arguments":{"expr":"2+2"}}]"#;
        let r = parse_tool_calls(text);
        assert_eq!(r.calls.len(), 1);
        assert_eq!(r.calls[0].name, "calc");
    }

    #[test]
    fn test_remainder_clean() {
        let text = "Text before. <tool_call>{\"name\":\"fn\",\"arguments\":{}}</tool_call> Text after.";
        let r = parse_tool_calls(text);
        assert_eq!(r.calls.len(), 1);
        assert!(r.remainder.contains("Text before."));
        assert!(r.remainder.contains("Text after."));
        assert!(!r.remainder.contains("<tool_call>"));
    }

    #[test]
    fn test_arguments_field() {
        let text = r#"<tool_call>{"name":"echo","arguments":{"msg":"hello world"}}</tool_call>"#;
        let r = parse_tool_calls(text);
        assert_eq!(r.calls[0].arguments, r#"{"msg":"hello world"}"#);
    }

    #[test]
    fn test_parameters_field_fallback() {
        // Some Mistral fine-tunes use "parameters" instead of "arguments"
        let text = r#"<tool_call>{"name":"lookup","parameters":{"key":"val"}}</tool_call>"#;
        let r = parse_tool_calls(text);
        assert_eq!(r.calls[0].name, "lookup");
        assert!(!r.calls[0].parse_error);
    }
}
